name: Python package
 
on: [push]
 
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        
    steps:
      - uses: actions/checkout@v3
      
        with:
          python-version: ${{ matrix.python-version }}
 
      - name: Test with pytest
        run: python -m unittest tests/tests.py
